@baseurl = http://localhost:3000
### Read one user
# @name readOneuser
GET {{baseurl}}/user/123

###create user
# @name createUser
POST {{baseurl}}/user
Content-Type: application/json

{
  "name": "Rafael",
  "email": "user@email.com",
  "password": "123456"
}


